org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
fabric_loader_version=0.19.3
fabric_api_version=0.155.2+26.1.2

mod_version=1.2.0
maven_group=io.github.ximu
archives_base_name=autofish-fabric
