org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

minecraft_version=26.1.2
minecraft_version_range=[26.1.2,26.1.3)
neo_version=26.1.2.87
neo_version_range=[26.1.2.71,)

mod_version=1.2.0
maven_group=io.github.ximu
archives_base_name=autofish
